### ISSUE TITLE
Namespace 'firebase' has no exported member 'Promise'.

### ISSUE THREAD

**Issue by PgPedroGabriel** [adriancarriger/angularfire2-offline#90]
i got this error

ERROR in node_modules/angularfire2-offline/database/angularfire2-interfaces.d.ts(4,32): error TS2694: Namespace 'firebase' has no exported member 'Promise'.
node_modules/angularfire2-offline/database/angularfire2-interfaces.d.ts(5,35): error TS2694: Namespace 'firebase' has no exported member 'Promise'.
node_modules/angularfire2-offline/database/angularfire2-interfaces.d.ts(6,35): error TS2694: Namespace 'firebase' has no exported member 'Promise'.
node_modules/angularfire2-offline/database/angularfire2-interfaces.d.ts(7,44): error TS2694: Namespace 'firebase' has no exported member 'Promise'.
node_modules/angularfire2-offline/database/object/afo-object-observable.d.ts(53,24): error TS2694: Namespace 'firebase' has no exported member 'Promise'.
node_modules/angularfire2-offline/database/object/afo-object-observable.d.ts(63,31): error TS2694: Namespace 'firebase' has no exported member 'Promise'.

**Comment by MayGo** [comment]
I also have this problem. Please merge pull-requests where these are fixed.

**Comment by sdanieljose** [comment]
HI! I'm with same problem, you find any solution @MayGo or @PgPedroGabriel?

I had this problem with the version of AngularFire2 ^5.0.0-rc.4 but with the version of example 4.0.0-rc.0 works!

**Comment by MayGo** [comment]
I made a choice to use firestore instead of firebase. Firestore has caching/offline support built in.

**Comment by vixson** [comment]
@MayGo  But would't that require you moving the whole data stored on the realtime DB down to firestore DB?

**Comment by MayGo** [comment]
@vixson yes.

**Comment by vixson** [comment]
Damn that is a gonna be stressful. please is there a way to move the data automatically on firebase

**Comment by 0xC0A1** [comment]
I have this issue too... Any known version working with firebase@4.12.1 ?

**Comment by vixson** [comment]
> I have this issue too... Any known version working with firebase@4.12.1 ?

Facing the same problem here. seriously
@PgPedroGabriel, @sdanieljose, @MayGo, @kevinrodriguez-io, unfortunately, you would have to stick with the old angularfire2 [version 40.0.-rc.0](https://www.npmjs.com/package/angularfire2/v/4.0.0-rc.0).
That is if you want to still use the firebase realtime.

**Comment by 0xC0A1** [comment]
In  the end It was easier for me to switch to firestore. Will keep using firestore in the future for all of my projects.
